language: java
jdk:
  - openjdk11
services:
  - docker
before_install:
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
script:
  - docker build -t developia/prevengic-api ./prevengic-api
  - docker tag developia/prevengic-api registry.heroku.com/prevengic-api/web
deploy:
  provider: script
  script:
    docker push developia/prevengic-api;
  on:
    branch: master