language: java
jdk:
  - openjdk13
services:
  - docker
before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
script:
  - docker build -f docker/Dockerfile -t registry.heroku.com/developia/prevengic-api .
  - docker push registry.heroku.com/prevengic-api/web