language: java
jdk:
  - openjdk13
services:
  - docker
before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin

script:
  - docker build -f docker/Dockerfile -t developia/prevengic-api .

deploy:
  provider: script
  script:
    docker push developia/prevengic-api;
  on:
    branch: master