version: "3"

services:

  prevengic-api:
    build: ./prevengic-api
    image: manudevelopia/prevengic-api:latest
    container_name: prevengic-api

  prevengic-db:
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=PREVENGIC_DB
    ports:
      - 5432:5432
    volumes:
      - ./sql/prevengic-api/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./sql/prevengic-api/data.sql:/docker-entrypoint-initdb.d/2-data.sql

