POST http://localhost:8080/composes
Content-Type: application/json

{
  "name":  "this is name",
  "description": "this is description",
  "ncas":  "ncas 1",
  "nce": "nce 1"
}

###

GET http://localhost:8080/composes/all
Accept: application/json

###

GET http://localhost:8080/composes?ncas=99
Accept: application/json

###